name: deployment

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]
    branches:
      - main

jobs:
  trigger-deployment-testing:
    runs-on: ubuntu-latest
    env:
      comments:
    steps:
      - name: Trigger testing deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: testing-ci-finish
          client-payload: '{"ref": "testing", "clickupCustomId": "${{ steps.get-clickup-task-custom-id.outputs.clickup_custom_id }}"}'