name: deployment

on:
  push:
    branches:
      - "testing"


      

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name || github.head_ref }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

      
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if cherry-pick and get parent SHA
        run: |
          PARENT_SHA=$(git log -1 --format="%P" $GITHUB_SHA | head -n 1)
          if [ -z "$PARENT_SHA" ]; then
            echo "This commit is not a cherry-pick."
          else
            echo "PARENT_SHA=$PARENT_SHA" >> $GITHUB_ENV
            echo "The parent SHA of the cherry-pick is $PARENT_SHA"
          fi

      - name: Search PR
        uses: actions/github-script@v7
        id: search-pr
        with:
          result-encoding: json
          script: |
            core.info(`search pr`);

            const { data: all_pull_requests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'main',
              state: 'open',
            })

            let targetCommit = null;
            let targetPR = null;
            for(const pr of all_pull_requests) {
              const commits = await github.rest.pulls.listCommits({
                owner: context.repo.owner,
                pull_number: pr.number,
                repo: context.repo.repo,
              })
              for(const commit of commits.data) {
                core.info(`commit: ${commit.sha}, github.sha: ${{github.PARENT_SHA}}`)
              }
            }

            return all_pull_requests;